In [1]:
# Update sklearn to prevent version mismatches
!pip install sklearn --upgrade

Requirement already up-to-date: sklearn in c:\users\sakon\anaconda3.1\lib\site-packages (0.0)


In [2]:
# install joblib. This will be used to save your model. 
# Restart your kernel after installing 
!pip install joblib

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer

# Read the CSV and Perform Basic Data Cleaning¶

In [4]:
df = pd.read_csv("Unemployment_cuy_Franklin_Butler.csv")
# Drop the null columns with all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

Cuy_Unpl  Franklin_Unpl  Butler_Unpl   Mean
0       9.3            9.9         11.2  10.13
1       9.7            9.7         11.0  10.13
2       9.0            9.6         10.8   9.80
3       8.5            9.1         10.2   9.27
4       8.4            8.7          9.7   8.93

# Select features columns

In [5]:
# Set features and set x values.
df.columns
#selected_features = df[['names', 'of', 'selected', 'features', 'here']]
selected_features = df[df.columns]
selected_features = selected_features.drop(columns = 'Mean')

In [6]:
# Drop columns from df. below based on the 3 classes results.
#selected_features  = selected_features.drop(columns = least_important_list)
X = selected_features
y = df['Mean'].to_numpy()
#y = Mean.values.reshape(-1, 1)
y

array([10.13, 10.13,  9.8 ,  9.27,  8.93,  9.33,  9.33,  8.97,  8.67,
        8.47,  8.57,  8.17,  8.93,  8.73,  8.23,  7.77,  8.07,  8.9 ,
        8.8 ,  8.3 ,  8.07,  7.67,  7.1 ,  7.1 ,  7.77,  7.73,  7.27,
        6.57,  6.7 ,  7.4 ,  7.47,  6.9 ,  6.47,  6.37,  6.2 ,  6.63,
        7.9 ,  7.6 ,  6.97,  6.37,  6.77,  7.6 ,  7.4 ,  7.  ,  6.83,
        6.8 ,  6.27,  5.97,  6.77,  6.7 ,  6.1 ,  5.03,  5.4 ,  5.9 ,
        6.  ,  5.57,  5.07,  4.8 ,  4.7 ,  4.57,  5.47,  5.2 ,  4.8 ,
        4.4 ,  4.73,  5.03,  4.83,  4.27,  4.17,  4.13,  4.2 ,  4.2 ,
        4.87,  4.93,  4.8 ,  4.43,  4.23,  5.  ,  4.87,  4.8 ,  4.83,
        4.7 ,  4.4 ,  4.67,  5.5 ,  5.4 ,  4.77,  4.4 ,  4.5 ,  5.1 ,
        5.03,  5.  ,  4.5 ,  4.17,  4.07,  4.  ,  4.53,  4.63,  4.3 ,
        4.  ,  4.  ,  4.93,  4.57,  4.23,  3.97,  3.9 ,  3.7 ,  4.  ,
        4.5 ,  4.1 ,  3.87,  3.3 ,  3.5 ,  4.23,  4.37,  4.  ,  3.7 ,
        3.5 ,  3.37,  3.4 ,  4.4 ,  4.3 ,  5.2 , 17.  , 13.87, 11.87,
       10.13,  9.6 ]

In [7]:
selected_features

Cuy_Unpl  Franklin_Unpl  Butler_Unpl
0         9.3            9.9         11.2
1         9.7            9.7         11.0
2         9.0            9.6         10.8
3         8.5            9.1         10.2
4         8.4            8.7          9.7
..        ...            ...          ...
123      22.9           13.9         14.2
124      18.1           11.6         11.9
125      15.2           10.6          9.8
126      13.1            9.1          8.2
127      11.6            9.1          8.1

[128 rows x 3 columns]

In [8]:
columns = selected_features.columns.to_list()

In [9]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
label_encoder.fit(y)
encoded_y = label_encoder.transform(y)

In [10]:
label_encoder.fit(y).transform(y)

array([83, 83, 82, 79, 77, 80, 80, 78, 73, 71, 72, 68, 77, 74, 69, 65, 67,
       76, 75, 70, 67, 63, 58, 58, 65, 64, 59, 49, 51, 60, 61, 55, 48, 47,
       45, 50, 66, 62, 56, 47, 52, 62, 60, 57, 54, 53, 46, 42, 52, 51, 44,
       33, 37, 41, 43, 40, 34, 28, 25, 22, 38, 36, 28, 18, 26, 33, 29, 15,
       12, 11, 13, 13, 30, 31, 28, 19, 14, 32, 30, 28, 29, 25, 18, 24, 39,
       37, 27, 18, 20, 35, 33, 32, 20, 12,  9,  8, 21, 23, 16,  8,  8, 31,
       22, 14,  7,  6,  4,  8, 20, 10,  5,  0,  3, 14, 17,  8,  4,  3,  1,
        2, 18, 16, 36, 86, 85, 84, 83, 81], dtype=int64)

In [11]:
for label, original_class in zip(encoded_y, y):
    print('Original Class: ' + str(original_class))
    print('Encoded Label: ' + str(label))
    print('-' * 12)

Original Class: 10.13
Encoded Label: 83
------------
Original Class: 10.13
Encoded Label: 83
------------
Original Class: 9.8
Encoded Label: 82
------------
Original Class: 9.27
Encoded Label: 79
------------
Original Class: 8.93
Encoded Label: 77
------------
Original Class: 9.33
Encoded Label: 80
------------
Original Class: 9.33
Encoded Label: 80
------------
Original Class: 8.97
Encoded Label: 78
------------
Original Class: 8.67
Encoded Label: 73
------------
Original Class: 8.47
Encoded Label: 71
------------
Original Class: 8.57
Encoded Label: 72
------------
Original Class: 8.17
Encoded Label: 68
------------
Original Class: 8.93
Encoded Label: 77
------------
Original Class: 8.73
Encoded Label: 74
------------
Original Class: 8.23
Encoded Label: 69
------------
Original Class: 7.77
Encoded Label: 65
------------
Original Class: 8.07
Encoded Label: 67
------------
Original Class: 8.9
Encoded Label: 76
------------
Original Class: 8.8
Encoded Label: 75
------------
Original Clas

In [12]:
encoded_y

array([83, 83, 82, 79, 77, 80, 80, 78, 73, 71, 72, 68, 77, 74, 69, 65, 67,
       76, 75, 70, 67, 63, 58, 58, 65, 64, 59, 49, 51, 60, 61, 55, 48, 47,
       45, 50, 66, 62, 56, 47, 52, 62, 60, 57, 54, 53, 46, 42, 52, 51, 44,
       33, 37, 41, 43, 40, 34, 28, 25, 22, 38, 36, 28, 18, 26, 33, 29, 15,
       12, 11, 13, 13, 30, 31, 28, 19, 14, 32, 30, 28, 29, 25, 18, 24, 39,
       37, 27, 18, 20, 35, 33, 32, 20, 12,  9,  8, 21, 23, 16,  8,  8, 31,
       22, 14,  7,  6,  4,  8, 20, 10,  5,  0,  3, 14, 17,  8,  4,  3,  1,
        2, 18, 16, 36, 86, 85, 84, 83, 81], dtype=int64)

In [13]:
encoded_y = encoded_y.reshape(-1,1)

In [14]:
print(X.shape, y.shape)

(128, 3) (128,)


In [15]:
encoded_y.shape

(128, 1)

# Create a Train Test Split

#Use Mean for the y values

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, encoded_y_train, encoded_y_test = train_test_split(X, encoded_y, random_state=1)

In [17]:
X_train.head()

Cuy_Unpl  Franklin_Unpl  Butler_Unpl
88        5.6            3.8          4.1
74        5.5            4.3          4.6
120       4.7            4.0          4.5
45        6.8            6.3          7.3
77        5.9            4.3          4.8

In [18]:
print(X_train.shape, encoded_y_train.shape)

(96, 3) (96, 1)


# Pre-processing
#Scale the data using the MinMaxScaler and perform some feature selection

In [19]:
# Scaling data
from sklearn.preprocessing import MinMaxScaler
X_scaler = MinMaxScaler().fit(X_train)
#y_scaler = MinMaxScaler().fit(encoded_y_train)

In [20]:
X_scaled_train = X_scaler.transform(X_train)
X_scaled_test = X_scaler.transform(X_test)
#y_scaled_train = y_scaler.transform(encoded_y_train)
#y_scaled_test = y_scaler.transform(encoded_y_test)

In [21]:
X_scaled_train

array([[0.10824742, 0.0733945 , 0.09009009],
       [0.10309278, 0.11926606, 0.13513514],
       [0.06185567, 0.09174312, 0.12612613],
       [0.17010309, 0.30275229, 0.37837838],
       [0.12371134, 0.11926606, 0.15315315],
       [0.03092784, 0.06422018, 0.07207207],
       [0.10824742, 0.08256881, 0.11711712],
       [0.08247423, 0.11009174, 0.15315315],
       [0.20103093, 0.34862385, 0.44144144],
       [0.10309278, 0.11009174, 0.15315315],
       [0.17010309, 0.13761468, 0.16216216],
       [0.22680412, 0.48623853, 0.57657658],
       [0.09793814, 0.11009174, 0.15315315],
       [0.1443299 , 0.27522936, 0.36036036],
       [0.49484536, 0.55963303, 0.45945946],
       [0.17010309, 0.32110092, 0.40540541],
       [0.21134021, 0.4587156 , 0.55855856],
       [0.41752577, 0.55963303, 0.45045045],
       [0.1443299 , 0.28440367, 0.37837838],
       [0.20618557, 0.40366972, 0.51351351],
       [0.1185567 , 0.12844037, 0.15315315],
       [0.13917526, 0.27522936, 0.34234234],
       [0.

In [22]:
encoded_y_train.ravel()

array([20, 28, 18, 53, 32,  6, 23, 25, 60, 29, 37, 72, 28, 48, 83, 56, 70,
       81, 49, 66, 32, 47, 31, 16, 33, 52, 33, 11, 12, 58, 45, 18,  3,  2,
       65, 62, 37, 59, 57, 65, 17, 30, 35, 51, 63, 13, 79,  8, 61, 85, 42,
        8, 73, 25, 38, 83,  3, 28, 58, 36, 18, 78, 86, 74, 27, 21,  9,  8,
       18, 12,  0, 69, 60, 51, 68, 39, 75, 31, 67, 44, 64, 80, 10, 13, 14,
       83, 67, 26, 28, 80, 19, 71, 30, 77,  8, 62], dtype=int64)

# Train the Model

In [23]:
encoded_y_train = encoded_y_train.ravel()
encoded_y_train

array([20, 28, 18, 53, 32,  6, 23, 25, 60, 29, 37, 72, 28, 48, 83, 56, 70,
       81, 49, 66, 32, 47, 31, 16, 33, 52, 33, 11, 12, 58, 45, 18,  3,  2,
       65, 62, 37, 59, 57, 65, 17, 30, 35, 51, 63, 13, 79,  8, 61, 85, 42,
        8, 73, 25, 38, 83,  3, 28, 58, 36, 18, 78, 86, 74, 27, 21,  9,  8,
       18, 12,  0, 69, 60, 51, 68, 39, 75, 31, 67, 44, 64, 80, 10, 13, 14,
       83, 67, 26, 28, 80, 19, 71, 30, 77,  8, 62], dtype=int64)

In [24]:
# random forest generator classifier
from sklearn.ensemble import RandomForestClassifier

In [25]:
rf = RandomForestClassifier()
rf = rf.fit(X_scaled_train, encoded_y_train)
rf.score(X_scaled_test, encoded_y_test)

0.09375

In [26]:
print(f"Training Data Score: {rf.score(X_scaled_train, encoded_y_train)}")
print(f"Testing Data Score: {rf.score(X_scaled_test, encoded_y_test)}")

Training Data Score: 1.0
Testing Data Score: 0.09375


In [27]:
# Random Forests in sklearn will automatically calculate feature importance
importances = rf.feature_importances_
importances

array([0.37039759, 0.3036469 , 0.32595552])

In [28]:
# Sort the features by their importance
sorted(zip(rf.feature_importances_, columns), reverse=True)

[(0.37039758779932536, 'Cuy_Unpl'),
 (0.32595551655656024, 'Butler_Unpl'),
 (0.30364689564411446, 'Franklin_Unpl')]

In [29]:
y

array([10.13, 10.13,  9.8 ,  9.27,  8.93,  9.33,  9.33,  8.97,  8.67,
        8.47,  8.57,  8.17,  8.93,  8.73,  8.23,  7.77,  8.07,  8.9 ,
        8.8 ,  8.3 ,  8.07,  7.67,  7.1 ,  7.1 ,  7.77,  7.73,  7.27,
        6.57,  6.7 ,  7.4 ,  7.47,  6.9 ,  6.47,  6.37,  6.2 ,  6.63,
        7.9 ,  7.6 ,  6.97,  6.37,  6.77,  7.6 ,  7.4 ,  7.  ,  6.83,
        6.8 ,  6.27,  5.97,  6.77,  6.7 ,  6.1 ,  5.03,  5.4 ,  5.9 ,
        6.  ,  5.57,  5.07,  4.8 ,  4.7 ,  4.57,  5.47,  5.2 ,  4.8 ,
        4.4 ,  4.73,  5.03,  4.83,  4.27,  4.17,  4.13,  4.2 ,  4.2 ,
        4.87,  4.93,  4.8 ,  4.43,  4.23,  5.  ,  4.87,  4.8 ,  4.83,
        4.7 ,  4.4 ,  4.67,  5.5 ,  5.4 ,  4.77,  4.4 ,  4.5 ,  5.1 ,
        5.03,  5.  ,  4.5 ,  4.17,  4.07,  4.  ,  4.53,  4.63,  4.3 ,
        4.  ,  4.  ,  4.93,  4.57,  4.23,  3.97,  3.9 ,  3.7 ,  4.  ,
        4.5 ,  4.1 ,  3.87,  3.3 ,  3.5 ,  4.23,  4.37,  4.  ,  3.7 ,
        3.5 ,  3.37,  3.4 ,  4.4 ,  4.3 ,  5.2 , 17.  , 13.87, 11.87,
       10.13,  9.6 ]

In [30]:
df_test = pd.DataFrame(y)
df_test = df_test.rename(columns = {0: 'Mean'}).reset_index()
df_test

index   Mean
0        0  10.13
1        1  10.13
2        2   9.80
3        3   9.27
4        4   8.93
..     ...    ...
123    123  17.00
124    124  13.87
125    125  11.87
126    126  10.13
127    127   9.60

[128 rows x 2 columns]

In [31]:
df_test_count = df_test.groupby(by = 'Mean').count()
df_test_count

index
Mean        
3.30       1
3.37       1
3.40       1
3.50       2
3.70       2
...      ...
9.80       1
10.13      3
11.87      1
13.87      1
17.00      1

[87 rows x 1 columns]

In [32]:
df_test_count = df_test.groupby(by = 'Mean').count()
df_test_count

index
Mean        
3.30       1
3.37       1
3.40       1
3.50       2
3.70       2
...      ...
9.80       1
10.13      3
11.87      1
13.87      1
17.00      1

[87 rows x 1 columns]

In [33]:
#Creating the dependent variable class
factor = pd.factorize(y)
df.Main = factor[0]
definitions = factor[1]
print(df.Main.head())
print(definitions)

C:\Users\sakon\anaconda3.1\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  This is separate from the ipykernel package so we can avoid doing imports until


AttributeError: 'numpy.ndarray' object has no attribute 'head'

In [42]:
# Predicting the Test set results
y_pred = rf.predict(X_scaled_test)

#Reverse factorize (converting y_pred from 0s,1s and 2s to Iris-setosa, Iris-versicolor and Iris-virginica
reversefactor = dict(zip(range(3),definitions))
y_test = np.vectorize(reversefactor.get)(encoded_y_test).ravel()

y_pred = np.vectorize(reversefactor.get)(y_pred)
# Making the Confusion Matrix
print(pd.crosstab(y_test, y_pred, rownames=['Actual result'], colnames=['Predicted result']))

Predicted result  9.27
Actual result         
9.8                  1


In [43]:
y

array([10.13, 10.13,  9.8 ,  9.27,  8.93,  9.33,  9.33,  8.97,  8.67,
        8.47,  8.57,  8.17,  8.93,  8.73,  8.23,  7.77,  8.07,  8.9 ,
        8.8 ,  8.3 ,  8.07,  7.67,  7.1 ,  7.1 ,  7.77,  7.73,  7.27,
        6.57,  6.7 ,  7.4 ,  7.47,  6.9 ,  6.47,  6.37,  6.2 ,  6.63,
        7.9 ,  7.6 ,  6.97,  6.37,  6.77,  7.6 ,  7.4 ,  7.  ,  6.83,
        6.8 ,  6.27,  5.97,  6.77,  6.7 ,  6.1 ,  5.03,  5.4 ,  5.9 ,
        6.  ,  5.57,  5.07,  4.8 ,  4.7 ,  4.57,  5.47,  5.2 ,  4.8 ,
        4.4 ,  4.73,  5.03,  4.83,  4.27,  4.17,  4.13,  4.2 ,  4.2 ,
        4.87,  4.93,  4.8 ,  4.43,  4.23,  5.  ,  4.87,  4.8 ,  4.83,
        4.7 ,  4.4 ,  4.67,  5.5 ,  5.4 ,  4.77,  4.4 ,  4.5 ,  5.1 ,
        5.03,  5.  ,  4.5 ,  4.17,  4.07,  4.  ,  4.53,  4.63,  4.3 ,
        4.  ,  4.  ,  4.93,  4.57,  4.23,  3.97,  3.9 ,  3.7 ,  4.  ,
        4.5 ,  4.1 ,  3.87,  3.3 ,  3.5 ,  4.23,  4.37,  4.  ,  3.7 ,
        3.5 ,  3.37,  3.4 ,  4.4 ,  4.3 ,  5.2 , 17.  , 13.87, 11.87,
       10.13,  9.6 ]

In [44]:
df.groupby(by = 'Mean').count()

Cuy_Unpl  Franklin_Unpl  Butler_Unpl
Mean                                       
3.30          1              1            1
3.37          1              1            1
3.40          1              1            1
3.50          2              2            2
3.70          2              2            2
...         ...            ...          ...
9.80          1              1            1
10.13         3              3            3
11.87         1              1            1
13.87         1              1            1
17.00         1              1            1

[87 rows x 3 columns]

In [45]:
# Create the RandomizedSearchCV model
from sklearn.model_selection import RandomizedSearchCV# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
#impurity decrease
impurity_decrease = [0, 1, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'min_impurity_decrease' : impurity_decrease,
               'max_features': max_features,
               'max_depth': max_depth,
               'criterion': ['gini', 'entropy'],
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap,
                'oob_score': [True, False]}
random_grid

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000],
 'min_impurity_decrease': [0, 1, 5, 10],
 'max_features': ['auto', 'sqrt'],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None],
 'criterion': ['gini', 'entropy'],
 'min_samples_split': [2, 5, 10],
 'min_samples_leaf': [1, 2, 4],
 'bootstrap': [True, False],
 'oob_score': [True, False]}

In [46]:
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, cv = 3, verbose = 2, n_iter = 100, random_state=42, n_jobs = -1)

In [ ]:
rf_random.fit(X_scaled_train, encoded_y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


C:\Users\sakon\anaconda3.1\lib\site-packages\sklearn\model_selection\_split.py:667: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  % (min_groups, self.n_splits)), UserWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   10.3s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  1.6min


In [ ]:
rf_random.best_params_

In [ ]:
rf_random.best_params_

In [ ]:
rf_random.best_estimator_

In [ ]:
rf_random.best_estimator_

In [ ]:
rf_random.score(X_scaled_test, encoded_y_test)

In [ ]:
rf_random.score(X_scaled_test, encoded_y_test)

In [ ]:
# Train the model with GridSearch
grid.fit(X_scaled_train, encoded_y_train.ravel())

In [55]:
print(grid.best_params_)
print(grid.best_score_)
print(grid.best_index_)

NameError: name 'grid' is not defined

In [58]:
def plot_coefficients(classifier, feature_names, top_features=15, class_num =1):

    coef = classifier.coef_[class_num].ravel()
    print("classifier.coef type",type(classifier.coef_))
    print("classifier.coef", classifier.coef_)
    print("type coef",type(coef))
    print("len(coeff)", len(coef))
    print("coef",coef)
    print("argsrt(coeff)",np.argsort(coef))
    top_positive_coefficients = np.argsort(coef)[-top_features:]
    print(len(top_positive_coefficients))
    print(type(top_positive_coefficients))
    print(top_positive_coefficients)
    top_negative_coefficients = np.argsort(coef)[:top_features]
    print(top_negative_coefficients)
    top_coefficients = np.hstack([top_negative_coefficients, top_positive_coefficients])
    print(top_coefficients)
    print(np.array(feature_names))
    #print(np.array(feature_names)[top_coefficients])
    #x_labels = np.array(feature_names)[top_coefficients]
    
 # create plot
    plt.figure(figsize=(15, 5))
    colors = ['red' if c < 0 else 'blue' for c in coef[top_coefficients]]
    print("coef[top_coefficients]",coef[top_coefficients])
    #print(feature_names[top_coefficients])
    plt.bar(np.arange(2 * top_features), coef[top_coefficients], color=colors)
    feature_names = np.array(feature_names)
    print("feature names",feature_names)
    print("top coefficients", top_coefficients)
    print("feature_name_top", feature_names[top_coefficients])
    features = feature_names[top_coefficients]
    plt.xticks(np.arange(1, 1 + 2 * top_features), features, rotation=60, ha='right')
    plt.show()

In [59]:
df_coef_1 = model.coef_[0]

NameError: name 'model' is not defined

In [62]:
cv = CountVectorizer()
cv.fit(selected_features)
print (len(cv.vocabulary_))
print(len(cv.get_feature_names()))
print (cv.get_feature_names())

3
3
['butler_unpl', 'cuy_unpl', 'franklin_unpl']


In [63]:
plot_coefficients(model, cv.get_feature_names(), 9,0)

NameError: name 'model' is not defined

In [64]:
plot_coefficients(model, cv.get_feature_names(), 9, 1)

NameError: name 'model' is not defined

In [65]:

plot_coefficients(model, cv.get_feature_names(), 9, 2)

NameError: name 'model' is not defined

In [66]:
def f_importances(coef, names):
    imp = coef
    print(imp)
    print(names)
    imp,names = zip(*sorted(zip(imp,names)))
    plt.barh(range(len(names)), imp, align='center')
    plt.yticks(range(len(names)), names)
    plt.show()

In [67]:
df_coef_0 = pd.DataFrame({'coef' : model.coef_[0],'abs(coef_)': abs(model.coef_[0]), 'name': columns})
df_coef_0=df_coef_0.sort_values('abs(coef_)', ascending = False)[-1:].reset_index()
df_coef_0

NameError: name 'model' is not defined

In [68]:
type(df_coef_0['name'])

NameError: name 'df_coef_0' is not defined

In [69]:
df_coef_1 = pd.DataFrame({'coef' : model.coef_[1],'abs(coef_)': abs(model.coef_[1]), 'name': columns})
df_coef_1=df_coef_1.sort_values('abs(coef_)', ascending = False)[-15:].reset_index()
df_coef_1

NameError: name 'model' is not defined

In [70]:
df_coef_2 = pd.DataFrame({'coef' : model.coef_[2],'abs(coef_)': abs(model.coef_[2]), 'name': columns})
df_coef_2=df_coef_2.sort_values('abs(coef_)', ascending = False)[-15:].reset_index()
df_coef_2

NameError: name 'model' is not defined

In [71]:
#out of the bottom 20 coefficients in each of the 3 classes these below are the ones common to all three.
df_least_important = df_coef_0.merge(df_coef_1, on = 'name', how = 'inner').merge(df_coef_2, on = 'name', how = 'inner')

NameError: name 'df_coef_0' is not defined

In [72]:
least_important_list = df_least_important['name'].to_list()
least_important_list

NameError: name 'df_least_important' is not defined

In [73]:
f_importances(model.coef_[0], columns)


NameError: name 'model' is not defined

In [74]:
len(columns)

3

In [75]:
pd.Series(abs(model.coef_[0]), index=columns).nlargest(20).plot(kind='barh')

NameError: name 'model' is not defined

In [76]:
pd.Series(abs(model.coef_[1]), index=columns).nlargest(20).plot(kind='barh')

NameError: name 'model' is not defined

In [77]:
pd.Series(abs(model.coef_[2]), index=columns).nlargest(20).plot(kind='barh')

NameError: name 'model' is not defined

In [78]:
from sklearn.feature_selection import SelectFromModel
model1 = SelectFromModel(lsvc, prefit=True)
X_new = model1.transform(X)

NameError: name 'lsvc' is not defined

In [79]:
X_new

NameError: name 'X_new' is not defined

# Hyperparameter Tuning
# Use GridSearchCV to tune the model's parameters



In [80]:
# Create the GridSearchCV model
from sklearn.model_selection import GridSearchCV
param_grid = {'C': [500,600, 700, 800 ,1000, 1100, 1200, 1300],
              'gamma': [1e-16, 1e-15,1e-14,1e-13]}
grid = GridSearchCV(model, param_grid, n_jobs = 10, verbose=3)

NameError: name 'model' is not defined

In [81]:
# Train the model with GridSearch
grid.fit(X_scaled_train, encoded_y_train.ravel())

NameError: name 'grid' is not defined

In [82]:
GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight='balanced', coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='linear', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=10,
             param_grid={'C': [500, 600, 700, 800, 1000, 1100, 1200, 1300],
                         'gamma': [1e-16, 1e-15, 1e-14, 1e-13]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

NameError: name 'nan' is not defined

In [83]:
grid

NameError: name 'grid' is not defined

In [84]:
sorted(grid.cv_results_.keys())

NameError: name 'grid' is not defined

In [85]:
print(grid.best_params_)
print(grid.best_score_)
print(grid.best_index_)


NameError: name 'grid' is not defined

In [86]:
grid[1]

NameError: name 'grid' is not defined

In [87]:
model.predict(X_scaled_test)

NameError: name 'model' is not defined

In [88]:
encoded_y_test.ravel()


array([16,  7, 40, 34, 47,  1, 36, 50, 55, 33, 20, 14, 77, 15, 22, 52, 46,
       22, 20,  4, 84, 82, 41,  4,  5, 14, 29, 54,  8, 43, 24, 76],
      dtype=int64)

In [89]:
df_results = pd.DataFrame({'col_1' : model.predict(X_scaled_test), 'col_2' : encoded_y_test.ravel()})
df_results

NameError: name 'model' is not defined

In [90]:
search.cv_results_['params']

NameError: name 'search' is not defined

In [91]:
model

NameError: name 'model' is not defined

In [93]:
# save your model by updating "your_name" with your name
# and "your_model" with your model variable
# be sure to turn this in to BCS
# if joblib fails to import, try running the command to install in terminal/git-bash
import joblib
filename = 'nakouma_svc.sav'
joblib.dump(model, filename)

NameError: name 'model' is not defined